# Generated by Django 5.2.17 on 2026-10-06 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SPAM', 'Spam'), ('HARASSMENT', 'Harcèlement'), ('FAKE_PROFILE', 'Faux profil'), ('INAPPROPRIATE', 'Contenu inapproprié'), ('OTHER', 'Autre')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('REVIEWED', 'Traité'), ('DISMISSED', 'Rejeté')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
