# Generated by Django 5.2.17 on 2026-10-06 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'signalement'},
        ),
        migrations.RemoveField(
            model_name='report',
            name='reported_user',
        ),
        migrations.AddField(
            model_name='report',
            name='target_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('USER', 'Profil'), ('PROJECT', 'Projet')], default='USER', max_length=10),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['target_type', 'target_id'], name='reports_rep_target__6b1f9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter', 'target_type', 'target_id'), name='unique_report_per_target'),
        ),
    ]
