# Generated by Django 5.2.17 on 2026-10-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_target_and_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='target_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('USER', 'Profil'), ('PROJECT', 'Projet')], max_length=10),
        ),
    ]
