# Generated by Django 5.2.17 on 2026-10-06 16:16

"""Catégories de compétences et types de preuve (contrat d'API DL-04).

Le niveau EXPERT est retiré : DL-15 ne prévoit que BEGINNER, INTERMEDIATE et
ADVANCED. Aucune donnée n'est concernée, le catalogue n'étant pas encore utilisé.
"""

from django.db import migrations, models

CATEGORIES = {
    "React": "FRONTEND",
    "Next.js": "FRONTEND",
    "TypeScript": "FRONTEND",
    "UI/UX Design": "DESIGN",
    "Flutter": "MOBILE",
    "Node.js": "BACKEND",
    "Python": "BACKEND",
    "FastAPI": "BACKEND",
    "PostgreSQL": "DATA",
    "Machine Learning": "DATA",
    "Docker": "DEVOPS",
    "Kubernetes": "DEVOPS",
    "CI/CD": "DEVOPS",
    "Linux": "DEVOPS",
}


def set_categories(apps, schema_editor):
    Skill = apps.get_model("skills", "Skill")
    for name, category in CATEGORIES.items():
        Skill.objects.filter(name=name).update(category=category)


def reset_categories(apps, schema_editor):
    Skill = apps.get_model("skills", "Skill")
    Skill.objects.filter(name__in=CATEGORIES).update(category="AUTRE")


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_seed_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('FRONTEND', 'Front-end'), ('BACKEND', 'Back-end'), ('MOBILE', 'Mobile'), ('DATA', 'Données'), ('DEVOPS', 'DevOps'), ('DESIGN', 'Design'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
        migrations.AddField(
            model_name='skillproof',
            name='kind',
            field=models.CharField(choices=[('PROJECT', 'Projet'), ('GITHUB_REPO', 'Dépôt GitHub'), ('OPEN_SOURCE', 'Contribution open source'), ('CERTIFICATION', 'Certification'), ('CHALLENGE', 'Challenge')], default='PROJECT', max_length=20),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Débutant'), ('INTERMEDIATE', 'Intermédiaire'), ('ADVANCED', 'Avancé')], default='BEGINNER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category'], name='skills_skil_categor_853dbf_idx'),
        ),
        migrations.RunPython(set_categories, reset_categories),
    ]
