# Generated by Django 5.2.17 on 2026-10-06 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('skills', '0003_skill_category_and_proof_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectjoinrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='projectjoinrequest',
            name='unique_join_request',
        ),
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, help_text='Démonstration en ligne (https uniquement).'),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, help_text='Dépôt du code (https uniquement).'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-created_at'], name='projects_pr_created_775fe7_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectjoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('project', 'applicant'), name='unique_pending_join_request'),
        ),
    ]
