# Generated by Django 5.2.17 on 2026-10-06 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PAIR_PROGRAMMING', 'Pair programming'), ('CODE_REVIEW', 'Revue de code'), ('MENTORAT', 'Mentorat'), ('DEBUGGING', 'Débogage'), ('PROJET_COMMUN', 'Projet commun'), ('PREPARATION_ENTRETIEN', "Préparation d'entretien"), ('ECHANGE_COMPETENCES', 'Échange de compétences'), ('DISCUSSION', 'Discussion')], max_length=30)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposé'), ('ACCEPTED', 'Accepté'), ('DECLINED', 'Refusé'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PROPOSED', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_requested', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='skills.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
