# Generated by Django 5.2.17 on 2026-10-06 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
        ('skills', '0003_skill_category_and_proof_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='pair_key',
            field=models.CharField(db_index=True, default='', editable=False, max_length=40),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['requester', 'status'], name='exchanges_e_request_c4d8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['partner', 'status'], name='exchanges_e_partner_f73a78_idx'),
        ),
        migrations.AddConstraint(
            model_name='exchange',
            constraint=models.CheckConstraint(condition=models.Q(('requester', models.F('partner')), _negated=True), name='exchange_requester_differs_from_partner'),
        ),
        migrations.AddConstraint(
            model_name='exchange',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PROPOSED')), fields=('pair_key',), name='unique_pending_exchange_per_pair'),
        ),
    ]
