# Generated by Django 5.2.17 on 2026-10-09 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=100)),
                ("arrows", models.JSONField(default=list)),
                ("score", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposé"),
                            ("ACTIVE", "Actif"),
                            ("DECLINED", "Refusé"),
                        ],
                        default="PROPOSED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "proposed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CircleMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACCEPTED", "Accepté"),
                            ("DECLINED", "Refusé"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="circles.circle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddConstraint(
            model_name="circle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PROPOSED", "ACTIVE"])),
                fields=("key",),
                name="unique_open_circle",
            ),
        ),
        migrations.AddConstraint(
            model_name="circlemember",
            constraint=models.UniqueConstraint(
                fields=("circle", "user"), name="unique_circle_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="circlemember",
            constraint=models.UniqueConstraint(
                fields=("circle", "position"), name="unique_circle_position"
            ),
        ),
    ]
