# Generated by Django 5.2.17 on 2026-10-06 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profil', 'verbose_name_plural': 'profils'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_demo',
            field=models.BooleanField(default=False, help_text="Profil de démonstration, étiqueté comme tel dans l'interface."),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country'], name='profiles_pr_country_0a6430_idx'),
        ),
    ]
