# Generated by Django 5.2.17 on 2026-10-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_index_and_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="contact",
            field=models.CharField(
                blank=True,
                help_text="Adresse e-mail ou lien https. Visible seulement par les partenaires d'un échange accepté.",
                max_length=200,
            ),
        ),
    ]
